### ISSUE TITLE
Can the chatbox remember the context when restart the server

### ISSUE THREAD

**Issue by p1k0pan** [jsmsj/GPT4#5]
Hi
I think the project is great. Is it possible to make the chatbox remember the context so that the user is able to continue chatting with the context that left behind last time?

**Comment by jsmsj** [comment]
It is possible for some models but not for all as, most of the models have limits like 1 or 5 gpt4 messages per day. This project tries to use multiple accounts to bypass that and all. So you cannot effectively transfer the chat context from one account to another.

**Comment by p1k0pan** [comment]
Thank you for the clarify
